import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildThemeContent } from '../src/generate-theme.mjs';
import { GHOSTTY_ANSI_NAMES, ghosttyCoreMapping, ghosttyDerivedMapping } from '../src/ghostty-mapping.mjs';
import { readAndValidateLock } from '../src/lock.mjs';

const distPath = path.resolve('dist/Static Noise');
const vendorPalettePath = path.resolve('vendor/static-noise/palette.json');
const HEX_COLOR_PATTERN = /^#[0-9A-Fa-f]{6}$/;

describe('Ghostty theme distribution file (dist/Static Noise)', () => {
  it('has exact match between committed dist/Static Noise and generator output', async () => {
    const lock = await readAndValidateLock();
    const palette = JSON.parse(await readFile(vendorPalettePath, 'utf8'));

    const expectedContent = buildThemeContent(palette, lock);
    const committedContent = await readFile(distPath, 'utf8');

    // This single assertion guarantees:
    // 1. dist/Static Noise was generated by buildThemeContent
    // 2. It has not been modified manually
    // 3. It is not stale relative to the current palette snapshot
    expect(committedContent).toBe(expectedContent);
  });

  it('contains valid Ghostty syntax with all mapped keys and 16 ANSI slots', async () => {
    const content = await readFile(distPath, 'utf8');

    const expectedKeys = [
      ...Object.keys(ghosttyCoreMapping),
      ...Object.keys(ghosttyDerivedMapping)
    ];

    for (const key of expectedKeys) {
      const match = content.match(new RegExp(`^${key} = (#[0-9A-Fa-f]{6})$`, 'm'));
      expect(match, `Key '${key}' missing or invalid in dist/Static Noise`).not.toBeNull();
    }

    for (let index = 0; index < GHOSTTY_ANSI_NAMES.length; index += 1) {
      const match = content.match(new RegExp(`^palette = ${index}=(#[0-9A-Fa-f]{6})$`, 'm'));
      expect(match, `ANSI slot ${index} missing or invalid in dist/Static Noise`).not.toBeNull();
    }
  });
});
